/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BondCandles model module.
 * @module model/BondCandles
 * @version 1.2.14
 */
class BondCandles {
    /**
     * Constructs a new <code>BondCandles</code>.
     * @alias module:model/BondCandles
     */
    constructor() { 
        
        BondCandles.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BondCandles</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BondCandles} obj Optional instance to populate.
     * @return {module:model/BondCandles} The populated <code>BondCandles</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BondCandles();

            if (data.hasOwnProperty('c')) {
                obj['c'] = ApiClient.convertToType(data['c'], ['Number']);
            }
            if (data.hasOwnProperty('t')) {
                obj['t'] = ApiClient.convertToType(data['t'], ['Number']);
            }
            if (data.hasOwnProperty('s')) {
                obj['s'] = ApiClient.convertToType(data['s'], 'String');
            }
        }
        return obj;
    }


}

/**
 * List of close prices for returned candles.
 * @member {Array.<Number>} c
 */
BondCandles.prototype['c'] = undefined;

/**
 * List of timestamp for returned candles.
 * @member {Array.<Number>} t
 */
BondCandles.prototype['t'] = undefined;

/**
 * Status of the response. This field can either be ok or no_data.
 * @member {String} s
 */
BondCandles.prototype['s'] = undefined;






export default BondCandles;

