/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BondYieldCurveInfo from './BondYieldCurveInfo';

/**
 * The BondYieldCurve model module.
 * @module model/BondYieldCurve
 * @version 1.2.19
 */
class BondYieldCurve {
    /**
     * Constructs a new <code>BondYieldCurve</code>.
     * @alias module:model/BondYieldCurve
     */
    constructor() { 
        
        BondYieldCurve.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BondYieldCurve</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BondYieldCurve} obj Optional instance to populate.
     * @return {module:model/BondYieldCurve} The populated <code>BondYieldCurve</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BondYieldCurve();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [BondYieldCurveInfo]);
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Array of data.
 * @member {Array.<module:model/BondYieldCurveInfo>} data
 */
BondYieldCurve.prototype['data'] = undefined;

/**
 * Bond's code
 * @member {String} code
 */
BondYieldCurve.prototype['code'] = undefined;






export default BondYieldCurve;

