/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompanyEarningsQualityScoreData model module.
 * @module model/CompanyEarningsQualityScoreData
 * @version 1.2.16
 */
class CompanyEarningsQualityScoreData {
    /**
     * Constructs a new <code>CompanyEarningsQualityScoreData</code>.
     * @alias module:model/CompanyEarningsQualityScoreData
     */
    constructor() { 
        
        CompanyEarningsQualityScoreData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompanyEarningsQualityScoreData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompanyEarningsQualityScoreData} obj Optional instance to populate.
     * @return {module:model/CompanyEarningsQualityScoreData} The populated <code>CompanyEarningsQualityScoreData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompanyEarningsQualityScoreData();

            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'String');
            }
            if (data.hasOwnProperty('growth')) {
                obj['growth'] = ApiClient.convertToType(data['growth'], 'Number');
            }
            if (data.hasOwnProperty('profitability')) {
                obj['profitability'] = ApiClient.convertToType(data['profitability'], 'Number');
            }
            if (data.hasOwnProperty('cashGenerationCapitalAllocation')) {
                obj['cashGenerationCapitalAllocation'] = ApiClient.convertToType(data['cashGenerationCapitalAllocation'], 'Number');
            }
            if (data.hasOwnProperty('leverage')) {
                obj['leverage'] = ApiClient.convertToType(data['leverage'], 'Number');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('letterScore')) {
                obj['letterScore'] = ApiClient.convertToType(data['letterScore'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Period
 * @member {String} period
 */
CompanyEarningsQualityScoreData.prototype['period'] = undefined;

/**
 * Growth Score
 * @member {Number} growth
 */
CompanyEarningsQualityScoreData.prototype['growth'] = undefined;

/**
 * Profitability Score
 * @member {Number} profitability
 */
CompanyEarningsQualityScoreData.prototype['profitability'] = undefined;

/**
 * Cash Generation and Capital Allocation
 * @member {Number} cashGenerationCapitalAllocation
 */
CompanyEarningsQualityScoreData.prototype['cashGenerationCapitalAllocation'] = undefined;

/**
 * Leverage Score
 * @member {Number} leverage
 */
CompanyEarningsQualityScoreData.prototype['leverage'] = undefined;

/**
 * Total Score
 * @member {Number} score
 */
CompanyEarningsQualityScoreData.prototype['score'] = undefined;

/**
 * Letter Score
 * @member {String} letterScore
 */
CompanyEarningsQualityScoreData.prototype['letterScore'] = undefined;






export default CompanyEarningsQualityScoreData;

