/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CongressionalTransaction model module.
 * @module model/CongressionalTransaction
 * @version 1.2.19
 */
class CongressionalTransaction {
    /**
     * Constructs a new <code>CongressionalTransaction</code>.
     * @alias module:model/CongressionalTransaction
     */
    constructor() { 
        
        CongressionalTransaction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CongressionalTransaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CongressionalTransaction} obj Optional instance to populate.
     * @return {module:model/CongressionalTransaction} The populated <code>CongressionalTransaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CongressionalTransaction();

            if (data.hasOwnProperty('amountFrom')) {
                obj['amountFrom'] = ApiClient.convertToType(data['amountFrom'], 'Number');
            }
            if (data.hasOwnProperty('amountTo')) {
                obj['amountTo'] = ApiClient.convertToType(data['amountTo'], 'Number');
            }
            if (data.hasOwnProperty('assetName')) {
                obj['assetName'] = ApiClient.convertToType(data['assetName'], 'String');
            }
            if (data.hasOwnProperty('filingDate')) {
                obj['filingDate'] = ApiClient.convertToType(data['filingDate'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ownerType')) {
                obj['ownerType'] = ApiClient.convertToType(data['ownerType'], 'String');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('transactionDate')) {
                obj['transactionDate'] = ApiClient.convertToType(data['transactionDate'], 'String');
            }
            if (data.hasOwnProperty('transactionType')) {
                obj['transactionType'] = ApiClient.convertToType(data['transactionType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Transaction amount from.
 * @member {Number} amountFrom
 */
CongressionalTransaction.prototype['amountFrom'] = undefined;

/**
 * Transaction amount to.
 * @member {Number} amountTo
 */
CongressionalTransaction.prototype['amountTo'] = undefined;

/**
 * Asset name.
 * @member {String} assetName
 */
CongressionalTransaction.prototype['assetName'] = undefined;

/**
 * Filing date.
 * @member {String} filingDate
 */
CongressionalTransaction.prototype['filingDate'] = undefined;

/**
 * Name of the representative.
 * @member {String} name
 */
CongressionalTransaction.prototype['name'] = undefined;

/**
 * Owner Type.
 * @member {String} ownerType
 */
CongressionalTransaction.prototype['ownerType'] = undefined;

/**
 * Position.
 * @member {String} position
 */
CongressionalTransaction.prototype['position'] = undefined;

/**
 * Symbol.
 * @member {String} symbol
 */
CongressionalTransaction.prototype['symbol'] = undefined;

/**
 * Transaction date.
 * @member {String} transactionDate
 */
CongressionalTransaction.prototype['transactionDate'] = undefined;

/**
 * Transaction type <code>Sale</code> or <code>Purchase</code>.
 * @member {String} transactionType
 */
CongressionalTransaction.prototype['transactionType'] = undefined;






export default CongressionalTransaction;

