/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EarningEstimate model module.
 * @module model/EarningEstimate
 * @version 0.0.1
 */
class EarningEstimate {
    /**
     * Constructs a new <code>EarningEstimate</code>.
     * @alias module:model/EarningEstimate
     */
    constructor() { 
        
        EarningEstimate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EarningEstimate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EarningEstimate} obj Optional instance to populate.
     * @return {module:model/EarningEstimate} The populated <code>EarningEstimate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EarningEstimate();

            if (data.hasOwnProperty('epsAvg')) {
                obj['epsAvg'] = ApiClient.convertToType(data['epsAvg'], 'Number');
            }
            if (data.hasOwnProperty('epsHigh')) {
                obj['epsHigh'] = ApiClient.convertToType(data['epsHigh'], 'Number');
            }
            if (data.hasOwnProperty('epsLow')) {
                obj['epsLow'] = ApiClient.convertToType(data['epsLow'], 'Number');
            }
            if (data.hasOwnProperty('numberAnalysts')) {
                obj['numberAnalysts'] = ApiClient.convertToType(data['numberAnalysts'], 'Number');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * Average EPS estimates.
 * @member {Number} epsAvg
 */
EarningEstimate.prototype['epsAvg'] = undefined;

/**
 * Highest estimate.
 * @member {Number} epsHigh
 */
EarningEstimate.prototype['epsHigh'] = undefined;

/**
 * Lowest estimate.
 * @member {Number} epsLow
 */
EarningEstimate.prototype['epsLow'] = undefined;

/**
 * Number of Analysts.
 * @member {Number} numberAnalysts
 */
EarningEstimate.prototype['numberAnalysts'] = undefined;

/**
 * Period.
 * @member {Date} period
 */
EarningEstimate.prototype['period'] = undefined;






export default EarningEstimate;

