/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmployeeCount model module.
 * @module model/EmployeeCount
 * @version 1.2.19
 */
class EmployeeCount {
    /**
     * Constructs a new <code>EmployeeCount</code>.
     * @alias module:model/EmployeeCount
     */
    constructor() { 
        
        EmployeeCount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmployeeCount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmployeeCount} obj Optional instance to populate.
     * @return {module:model/EmployeeCount} The populated <code>EmployeeCount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmployeeCount();

            if (data.hasOwnProperty('atDate')) {
                obj['atDate'] = ApiClient.convertToType(data['atDate'], 'String');
            }
            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Date of the reading
 * @member {String} atDate
 */
EmployeeCount.prototype['atDate'] = undefined;

/**
 * Value
 * @member {Number} employee
 */
EmployeeCount.prototype['employee'] = undefined;






export default EmployeeCount;

