/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Filing model module.
 * @module model/Filing
 * @version 1.1.3
 */
class Filing {
    /**
     * Constructs a new <code>Filing</code>.
     * @alias module:model/Filing
     */
    constructor() { 
        
        Filing.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Filing</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Filing} obj Optional instance to populate.
     * @return {module:model/Filing} The populated <code>Filing</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Filing();

            if (data.hasOwnProperty('accessNumber')) {
                obj['accessNumber'] = ApiClient.convertToType(data['accessNumber'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('cik')) {
                obj['cik'] = ApiClient.convertToType(data['cik'], 'String');
            }
            if (data.hasOwnProperty('form')) {
                obj['form'] = ApiClient.convertToType(data['form'], 'String');
            }
            if (data.hasOwnProperty('filedDate')) {
                obj['filedDate'] = ApiClient.convertToType(data['filedDate'], 'Date');
            }
            if (data.hasOwnProperty('acceptedDate')) {
                obj['acceptedDate'] = ApiClient.convertToType(data['acceptedDate'], 'Date');
            }
            if (data.hasOwnProperty('reportUrl')) {
                obj['reportUrl'] = ApiClient.convertToType(data['reportUrl'], 'String');
            }
            if (data.hasOwnProperty('filingUrl')) {
                obj['filingUrl'] = ApiClient.convertToType(data['filingUrl'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Access number.
 * @member {String} accessNumber
 */
Filing.prototype['accessNumber'] = undefined;

/**
 * Symbol.
 * @member {String} symbol
 */
Filing.prototype['symbol'] = undefined;

/**
 * CIK.
 * @member {String} cik
 */
Filing.prototype['cik'] = undefined;

/**
 * Form type.
 * @member {String} form
 */
Filing.prototype['form'] = undefined;

/**
 * Filed date <code>%Y-%m-%d %H:%M:%S</code>.
 * @member {Date} filedDate
 */
Filing.prototype['filedDate'] = undefined;

/**
 * Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
 * @member {Date} acceptedDate
 */
Filing.prototype['acceptedDate'] = undefined;

/**
 * Report's URL.
 * @member {String} reportUrl
 */
Filing.prototype['reportUrl'] = undefined;

/**
 * Filing's URL.
 * @member {String} filingUrl
 */
Filing.prototype['filingUrl'] = undefined;






export default Filing;

