/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsiderSentimentsData model module.
 * @module model/InsiderSentimentsData
 * @version 1.2.18
 */
class InsiderSentimentsData {
    /**
     * Constructs a new <code>InsiderSentimentsData</code>.
     * @alias module:model/InsiderSentimentsData
     */
    constructor() { 
        
        InsiderSentimentsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InsiderSentimentsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsiderSentimentsData} obj Optional instance to populate.
     * @return {module:model/InsiderSentimentsData} The populated <code>InsiderSentimentsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsiderSentimentsData();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('year')) {
                obj['year'] = ApiClient.convertToType(data['year'], 'Number');
            }
            if (data.hasOwnProperty('month')) {
                obj['month'] = ApiClient.convertToType(data['month'], 'Number');
            }
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('mspr')) {
                obj['mspr'] = ApiClient.convertToType(data['mspr'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Symbol.
 * @member {String} symbol
 */
InsiderSentimentsData.prototype['symbol'] = undefined;

/**
 * Year.
 * @member {Number} year
 */
InsiderSentimentsData.prototype['year'] = undefined;

/**
 * Month.
 * @member {Number} month
 */
InsiderSentimentsData.prototype['month'] = undefined;

/**
 * Net buying/selling from all insiders' transactions.
 * @member {Number} change
 */
InsiderSentimentsData.prototype['change'] = undefined;

/**
 * Monthly share purchase ratio.
 * @member {Number} mspr
 */
InsiderSentimentsData.prototype['mspr'] = undefined;






export default InsiderSentimentsData;

