/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstitutionalPortfolioInfo from './InstitutionalPortfolioInfo';

/**
 * The InstitutionalPortfolioGroup model module.
 * @module model/InstitutionalPortfolioGroup
 * @version 1.2.18
 */
class InstitutionalPortfolioGroup {
    /**
     * Constructs a new <code>InstitutionalPortfolioGroup</code>.
     * @alias module:model/InstitutionalPortfolioGroup
     */
    constructor() { 
        
        InstitutionalPortfolioGroup.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstitutionalPortfolioGroup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionalPortfolioGroup} obj Optional instance to populate.
     * @return {module:model/InstitutionalPortfolioGroup} The populated <code>InstitutionalPortfolioGroup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionalPortfolioGroup();

            if (data.hasOwnProperty('reportDate')) {
                obj['reportDate'] = ApiClient.convertToType(data['reportDate'], 'String');
            }
            if (data.hasOwnProperty('filingDate')) {
                obj['filingDate'] = ApiClient.convertToType(data['filingDate'], 'String');
            }
            if (data.hasOwnProperty('portfolio')) {
                obj['portfolio'] = ApiClient.convertToType(data['portfolio'], [InstitutionalPortfolioInfo]);
            }
        }
        return obj;
    }


}

/**
 * Report date.
 * @member {String} reportDate
 */
InstitutionalPortfolioGroup.prototype['reportDate'] = undefined;

/**
 * Filing date.
 * @member {String} filingDate
 */
InstitutionalPortfolioGroup.prototype['filingDate'] = undefined;

/**
 * Array of positions.
 * @member {Array.<module:model/InstitutionalPortfolioInfo>} portfolio
 */
InstitutionalPortfolioGroup.prototype['portfolio'] = undefined;






export default InstitutionalPortfolioGroup;

