/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstitutionalProfileInfo model module.
 * @module model/InstitutionalProfileInfo
 * @version 1.2.18
 */
class InstitutionalProfileInfo {
    /**
     * Constructs a new <code>InstitutionalProfileInfo</code>.
     * @alias module:model/InstitutionalProfileInfo
     */
    constructor() { 
        
        InstitutionalProfileInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstitutionalProfileInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionalProfileInfo} obj Optional instance to populate.
     * @return {module:model/InstitutionalProfileInfo} The populated <code>InstitutionalProfileInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionalProfileInfo();

            if (data.hasOwnProperty('cik')) {
                obj['cik'] = ApiClient.convertToType(data['cik'], 'String');
            }
            if (data.hasOwnProperty('firmType')) {
                obj['firmType'] = ApiClient.convertToType(data['firmType'], 'String');
            }
            if (data.hasOwnProperty('manager')) {
                obj['manager'] = ApiClient.convertToType(data['manager'], 'String');
            }
            if (data.hasOwnProperty('philosophy')) {
                obj['philosophy'] = ApiClient.convertToType(data['philosophy'], 'String');
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], 'String');
            }
            if (data.hasOwnProperty('profileImg')) {
                obj['profileImg'] = ApiClient.convertToType(data['profileImg'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Investor's company CIK.
 * @member {String} cik
 */
InstitutionalProfileInfo.prototype['cik'] = undefined;

/**
 * Firm type.
 * @member {String} firmType
 */
InstitutionalProfileInfo.prototype['firmType'] = undefined;

/**
 * Manager.
 * @member {String} manager
 */
InstitutionalProfileInfo.prototype['manager'] = undefined;

/**
 * Investing philosophy.
 * @member {String} philosophy
 */
InstitutionalProfileInfo.prototype['philosophy'] = undefined;

/**
 * Profile info.
 * @member {String} profile
 */
InstitutionalProfileInfo.prototype['profile'] = undefined;

/**
 * Profile image.
 * @member {String} profileImg
 */
InstitutionalProfileInfo.prototype['profileImg'] = undefined;






export default InstitutionalProfileInfo;

