/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InstitutionalOwnershipGroup from './InstitutionalOwnershipGroup';

/**
 * The InstitutionalOwnership model module.
 * @module model/InstitutionalOwnership
 * @version 1.2.18
 */
class InstitutionalOwnership {
    /**
     * Constructs a new <code>InstitutionalOwnership</code>.
     * @alias module:model/InstitutionalOwnership
     */
    constructor() { 
        
        InstitutionalOwnership.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstitutionalOwnership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionalOwnership} obj Optional instance to populate.
     * @return {module:model/InstitutionalOwnership} The populated <code>InstitutionalOwnership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionalOwnership();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('cusip')) {
                obj['cusip'] = ApiClient.convertToType(data['cusip'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [InstitutionalOwnershipGroup]);
            }
        }
        return obj;
    }


}

/**
 * Symbol.
 * @member {String} symbol
 */
InstitutionalOwnership.prototype['symbol'] = undefined;

/**
 * Cusip.
 * @member {String} cusip
 */
InstitutionalOwnership.prototype['cusip'] = undefined;

/**
 * Array of institutional investors.
 * @member {Array.<module:model/InstitutionalOwnershipGroup>} data
 */
InstitutionalOwnership.prototype['data'] = undefined;






export default InstitutionalOwnership;

