/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstitutionalOwnershipInfo model module.
 * @module model/InstitutionalOwnershipInfo
 * @version 1.2.19
 */
class InstitutionalOwnershipInfo {
    /**
     * Constructs a new <code>InstitutionalOwnershipInfo</code>.
     * @alias module:model/InstitutionalOwnershipInfo
     */
    constructor() { 
        
        InstitutionalOwnershipInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstitutionalOwnershipInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstitutionalOwnershipInfo} obj Optional instance to populate.
     * @return {module:model/InstitutionalOwnershipInfo} The populated <code>InstitutionalOwnershipInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstitutionalOwnershipInfo();

            if (data.hasOwnProperty('cik')) {
                obj['cik'] = ApiClient.convertToType(data['cik'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('putCall')) {
                obj['putCall'] = ApiClient.convertToType(data['putCall'], 'String');
            }
            if (data.hasOwnProperty('change')) {
                obj['change'] = ApiClient.convertToType(data['change'], 'Number');
            }
            if (data.hasOwnProperty('noVoting')) {
                obj['noVoting'] = ApiClient.convertToType(data['noVoting'], 'Number');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
            if (data.hasOwnProperty('share')) {
                obj['share'] = ApiClient.convertToType(data['share'], 'Number');
            }
            if (data.hasOwnProperty('sharedVoting')) {
                obj['sharedVoting'] = ApiClient.convertToType(data['sharedVoting'], 'Number');
            }
            if (data.hasOwnProperty('soleVoting')) {
                obj['soleVoting'] = ApiClient.convertToType(data['soleVoting'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Investor's company CIK.
 * @member {String} cik
 */
InstitutionalOwnershipInfo.prototype['cik'] = undefined;

/**
 * Firm's name.
 * @member {String} name
 */
InstitutionalOwnershipInfo.prototype['name'] = undefined;

/**
 * <code>put</code> or <code>call</code> for options.
 * @member {String} putCall
 */
InstitutionalOwnershipInfo.prototype['putCall'] = undefined;

/**
 * Number of shares change.
 * @member {Number} change
 */
InstitutionalOwnershipInfo.prototype['change'] = undefined;

/**
 * Number of shares with no voting rights.
 * @member {Number} noVoting
 */
InstitutionalOwnershipInfo.prototype['noVoting'] = undefined;

/**
 * Percentage of portfolio.
 * @member {Number} percentage
 */
InstitutionalOwnershipInfo.prototype['percentage'] = undefined;

/**
 * News score.
 * @member {Number} share
 */
InstitutionalOwnershipInfo.prototype['share'] = undefined;

/**
 * Number of shares with shared voting rights.
 * @member {Number} sharedVoting
 */
InstitutionalOwnershipInfo.prototype['sharedVoting'] = undefined;

/**
 * Number of shares with sole voting rights.
 * @member {Number} soleVoting
 */
InstitutionalOwnershipInfo.prototype['soleVoting'] = undefined;

/**
 * Position value.
 * @member {Number} value
 */
InstitutionalOwnershipInfo.prototype['value'] = undefined;






export default InstitutionalOwnershipInfo;

