/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InvestmentThemePortfolio from './InvestmentThemePortfolio';

/**
 * The InvestmentThemes model module.
 * @module model/InvestmentThemes
 * @version 1.2.7
 */
class InvestmentThemes {
    /**
     * Constructs a new <code>InvestmentThemes</code>.
     * @alias module:model/InvestmentThemes
     */
    constructor() { 
        
        InvestmentThemes.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvestmentThemes</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvestmentThemes} obj Optional instance to populate.
     * @return {module:model/InvestmentThemes} The populated <code>InvestmentThemes</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestmentThemes();

            if (data.hasOwnProperty('theme')) {
                obj['theme'] = ApiClient.convertToType(data['theme'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [InvestmentThemePortfolio]);
            }
        }
        return obj;
    }


}

/**
 * Investment theme
 * @member {String} theme
 */
InvestmentThemes.prototype['theme'] = undefined;

/**
 * Investment theme portfolio.
 * @member {Array.<module:model/InvestmentThemePortfolio>} data
 */
InvestmentThemes.prototype['data'] = undefined;






export default InvestmentThemes;

