/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LobbyingData from './LobbyingData';

/**
 * The LobbyingResult model module.
 * @module model/LobbyingResult
 * @version 1.2.15
 */
class LobbyingResult {
    /**
     * Constructs a new <code>LobbyingResult</code>.
     * @alias module:model/LobbyingResult
     */
    constructor() { 
        
        LobbyingResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LobbyingResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LobbyingResult} obj Optional instance to populate.
     * @return {module:model/LobbyingResult} The populated <code>LobbyingResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LobbyingResult();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [LobbyingData]);
            }
        }
        return obj;
    }


}

/**
 * Symbol.
 * @member {String} symbol
 */
LobbyingResult.prototype['symbol'] = undefined;

/**
 * Array of lobbying activities.
 * @member {Array.<module:model/LobbyingData>} data
 */
LobbyingResult.prototype['data'] = undefined;






export default LobbyingResult;

