/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MajorPressReleases model module.
 * @module model/MajorPressReleases
 * @version 1.2.2
 */
class MajorPressReleases {
    /**
     * Constructs a new <code>MajorPressReleases</code>.
     * @alias module:model/MajorPressReleases
     */
    constructor() { 
        
        MajorPressReleases.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MajorPressReleases</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MajorPressReleases} obj Optional instance to populate.
     * @return {module:model/MajorPressReleases} The populated <code>MajorPressReleases</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MajorPressReleases();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('majorDevelopment')) {
                obj['majorDevelopment'] = ApiClient.convertToType(data['majorDevelopment'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * Company symbol.
 * @member {String} symbol
 */
MajorPressReleases.prototype['symbol'] = undefined;

/**
 * Array of major developments.
 * @member {Array.<Object>} majorDevelopment
 */
MajorPressReleases.prototype['majorDevelopment'] = undefined;






export default MajorPressReleases;

