/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MutualFundSectorExposureData from './MutualFundSectorExposureData';

/**
 * The MutualFundSectorExposure model module.
 * @module model/MutualFundSectorExposure
 * @version 1.2.11
 */
class MutualFundSectorExposure {
    /**
     * Constructs a new <code>MutualFundSectorExposure</code>.
     * @alias module:model/MutualFundSectorExposure
     */
    constructor() { 
        
        MutualFundSectorExposure.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MutualFundSectorExposure</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MutualFundSectorExposure} obj Optional instance to populate.
     * @return {module:model/MutualFundSectorExposure} The populated <code>MutualFundSectorExposure</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MutualFundSectorExposure();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('sectorExposure')) {
                obj['sectorExposure'] = ApiClient.convertToType(data['sectorExposure'], [MutualFundSectorExposureData]);
            }
        }
        return obj;
    }


}

/**
 * Mutual symbol.
 * @member {String} symbol
 */
MutualFundSectorExposure.prototype['symbol'] = undefined;

/**
 * Array of sector and exposure levels.
 * @member {Array.<module:model/MutualFundSectorExposureData>} sectorExposure
 */
MutualFundSectorExposure.prototype['sectorExposure'] = undefined;






export default MutualFundSectorExposure;

