/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MutualFundEetPai model module.
 * @module model/MutualFundEetPai
 * @version 1.2.19
 */
class MutualFundEetPai {
    /**
     * Constructs a new <code>MutualFundEetPai</code>.
     * @alias module:model/MutualFundEetPai
     */
    constructor() { 
        
        MutualFundEetPai.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MutualFundEetPai</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MutualFundEetPai} obj Optional instance to populate.
     * @return {module:model/MutualFundEetPai} The populated <code>MutualFundEetPai</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MutualFundEetPai();

            if (data.hasOwnProperty('isin')) {
                obj['isin'] = ApiClient.convertToType(data['isin'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
        }
        return obj;
    }


}

/**
 * ISIN.
 * @member {String} isin
 */
MutualFundEetPai.prototype['isin'] = undefined;

/**
 * @member {Object} data
 */
MutualFundEetPai.prototype['data'] = undefined;






export default MutualFundEetPai;

