/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TradesLastPriceUpdates model module.
 * @module model/TradesLastPriceUpdates
 * @version 1.1.4
 */
class TradesLastPriceUpdates {
    /**
     * Constructs a new <code>TradesLastPriceUpdates</code>.
     * @alias module:model/TradesLastPriceUpdates
     */
    constructor() { 
        
        TradesLastPriceUpdates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TradesLastPriceUpdates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TradesLastPriceUpdates} obj Optional instance to populate.
     * @return {module:model/TradesLastPriceUpdates} The populated <code>TradesLastPriceUpdates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TradesLastPriceUpdates();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * Message type.
 * @member {String} type
 */
TradesLastPriceUpdates.prototype['type'] = undefined;

/**
 * List of trades or price updates.
 * @member {Array.<Object>} data
 */
TradesLastPriceUpdates.prototype['data'] = undefined;






export default TradesLastPriceUpdates;

