/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UsaSpending model module.
 * @module model/UsaSpending
 * @version 1.2.16
 */
class UsaSpending {
    /**
     * Constructs a new <code>UsaSpending</code>.
     * @alias module:model/UsaSpending
     */
    constructor() { 
        
        UsaSpending.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UsaSpending</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UsaSpending} obj Optional instance to populate.
     * @return {module:model/UsaSpending} The populated <code>UsaSpending</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UsaSpending();

            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('recipientName')) {
                obj['recipientName'] = ApiClient.convertToType(data['recipientName'], 'String');
            }
            if (data.hasOwnProperty('recipientParentName')) {
                obj['recipientParentName'] = ApiClient.convertToType(data['recipientParentName'], 'String');
            }
            if (data.hasOwnProperty('awardDescription')) {
                obj['awardDescription'] = ApiClient.convertToType(data['awardDescription'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('actionDate')) {
                obj['actionDate'] = ApiClient.convertToType(data['actionDate'], 'String');
            }
            if (data.hasOwnProperty('totalValue')) {
                obj['totalValue'] = ApiClient.convertToType(data['totalValue'], 'Number');
            }
            if (data.hasOwnProperty('performanceStartDate')) {
                obj['performanceStartDate'] = ApiClient.convertToType(data['performanceStartDate'], 'String');
            }
            if (data.hasOwnProperty('performanceEndDate')) {
                obj['performanceEndDate'] = ApiClient.convertToType(data['performanceEndDate'], 'String');
            }
            if (data.hasOwnProperty('awardingAgencyName')) {
                obj['awardingAgencyName'] = ApiClient.convertToType(data['awardingAgencyName'], 'String');
            }
            if (data.hasOwnProperty('awardingSubAgencyName')) {
                obj['awardingSubAgencyName'] = ApiClient.convertToType(data['awardingSubAgencyName'], 'String');
            }
            if (data.hasOwnProperty('awardingOfficeName')) {
                obj['awardingOfficeName'] = ApiClient.convertToType(data['awardingOfficeName'], 'String');
            }
            if (data.hasOwnProperty('performanceCountry')) {
                obj['performanceCountry'] = ApiClient.convertToType(data['performanceCountry'], 'String');
            }
            if (data.hasOwnProperty('performanceCity')) {
                obj['performanceCity'] = ApiClient.convertToType(data['performanceCity'], 'String');
            }
            if (data.hasOwnProperty('performanceCounty')) {
                obj['performanceCounty'] = ApiClient.convertToType(data['performanceCounty'], 'String');
            }
            if (data.hasOwnProperty('performanceState')) {
                obj['performanceState'] = ApiClient.convertToType(data['performanceState'], 'String');
            }
            if (data.hasOwnProperty('performanceZipCode')) {
                obj['performanceZipCode'] = ApiClient.convertToType(data['performanceZipCode'], 'String');
            }
            if (data.hasOwnProperty('performanceCongressionalDistrict')) {
                obj['performanceCongressionalDistrict'] = ApiClient.convertToType(data['performanceCongressionalDistrict'], 'String');
            }
            if (data.hasOwnProperty('naicsCode')) {
                obj['naicsCode'] = ApiClient.convertToType(data['naicsCode'], 'String');
            }
            if (data.hasOwnProperty('permalink')) {
                obj['permalink'] = ApiClient.convertToType(data['permalink'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Symbol.
 * @member {String} symbol
 */
UsaSpending.prototype['symbol'] = undefined;

/**
 * Company's name.
 * @member {String} recipientName
 */
UsaSpending.prototype['recipientName'] = undefined;

/**
 * Company's name.
 * @member {String} recipientParentName
 */
UsaSpending.prototype['recipientParentName'] = undefined;

/**
 * Description.
 * @member {String} awardDescription
 */
UsaSpending.prototype['awardDescription'] = undefined;

/**
 * Recipient's country.
 * @member {String} country
 */
UsaSpending.prototype['country'] = undefined;

/**
 * Period.
 * @member {String} actionDate
 */
UsaSpending.prototype['actionDate'] = undefined;

/**
 * Income reported by lobbying firms.
 * @member {Number} totalValue
 */
UsaSpending.prototype['totalValue'] = undefined;

/**
 * Performance start date.
 * @member {String} performanceStartDate
 */
UsaSpending.prototype['performanceStartDate'] = undefined;

/**
 * Performance end date.
 * @member {String} performanceEndDate
 */
UsaSpending.prototype['performanceEndDate'] = undefined;

/**
 * Award agency.
 * @member {String} awardingAgencyName
 */
UsaSpending.prototype['awardingAgencyName'] = undefined;

/**
 * Award sub-agency.
 * @member {String} awardingSubAgencyName
 */
UsaSpending.prototype['awardingSubAgencyName'] = undefined;

/**
 * Award office name.
 * @member {String} awardingOfficeName
 */
UsaSpending.prototype['awardingOfficeName'] = undefined;

/**
 * Performance country.
 * @member {String} performanceCountry
 */
UsaSpending.prototype['performanceCountry'] = undefined;

/**
 * Performance city.
 * @member {String} performanceCity
 */
UsaSpending.prototype['performanceCity'] = undefined;

/**
 * Performance county.
 * @member {String} performanceCounty
 */
UsaSpending.prototype['performanceCounty'] = undefined;

/**
 * Performance state.
 * @member {String} performanceState
 */
UsaSpending.prototype['performanceState'] = undefined;

/**
 * Performance zip code.
 * @member {String} performanceZipCode
 */
UsaSpending.prototype['performanceZipCode'] = undefined;

/**
 * Performance congressional district.
 * @member {String} performanceCongressionalDistrict
 */
UsaSpending.prototype['performanceCongressionalDistrict'] = undefined;

/**
 * NAICS code.
 * @member {String} naicsCode
 */
UsaSpending.prototype['naicsCode'] = undefined;

/**
 * Permalink.
 * @member {String} permalink
 */
UsaSpending.prototype['permalink'] = undefined;






export default UsaSpending;

