/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.CompanyEarningsQualityScoreData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyEarningsQualityScoreData', function() {
    it('should create an instance of CompanyEarningsQualityScoreData', function() {
      // uncomment below and update the code to test CompanyEarningsQualityScoreData
      //var instane = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be.a(finnhub.CompanyEarningsQualityScoreData);
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property growth (base name: "growth")', function() {
      // uncomment below and update the code to test the property growth
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property profitability (base name: "profitability")', function() {
      // uncomment below and update the code to test the property profitability
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property cashGenerationCapitalAllocation (base name: "cashGenerationCapitalAllocation")', function() {
      // uncomment below and update the code to test the property cashGenerationCapitalAllocation
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property leverage (base name: "leverage")', function() {
      // uncomment below and update the code to test the property leverage
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

    it('should have the property letterScore (base name: "letterScore")', function() {
      // uncomment below and update the code to test the property letterScore
      //var instance = new finnhub.CompanyEarningsQualityScoreData();
      //expect(instance).to.be();
    });

  });

}));
