/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.CompanyProfile2();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CompanyProfile2', function() {
    it('should create an instance of CompanyProfile2', function() {
      // uncomment below and update the code to test CompanyProfile2
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be.a(finnhub.CompanyProfile2);
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property exchange (base name: "exchange")', function() {
      // uncomment below and update the code to test the property exchange
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property ticker (base name: "ticker")', function() {
      // uncomment below and update the code to test the property ticker
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property ipo (base name: "ipo")', function() {
      // uncomment below and update the code to test the property ipo
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property marketCapitalization (base name: "marketCapitalization")', function() {
      // uncomment below and update the code to test the property marketCapitalization
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property shareOutstanding (base name: "shareOutstanding")', function() {
      // uncomment below and update the code to test the property shareOutstanding
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property logo (base name: "logo")', function() {
      // uncomment below and update the code to test the property logo
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property weburl (base name: "weburl")', function() {
      // uncomment below and update the code to test the property weburl
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

    it('should have the property finnhubIndustry (base name: "finnhubIndustry")', function() {
      // uncomment below and update the code to test the property finnhubIndustry
      //var instane = new finnhub.CompanyProfile2();
      //expect(instance).to.be();
    });

  });

}));
