/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.CongressionalTransaction();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CongressionalTransaction', function() {
    it('should create an instance of CongressionalTransaction', function() {
      // uncomment below and update the code to test CongressionalTransaction
      //var instane = new finnhub.CongressionalTransaction();
      //expect(instance).to.be.a(finnhub.CongressionalTransaction);
    });

    it('should have the property amountFrom (base name: "amountFrom")', function() {
      // uncomment below and update the code to test the property amountFrom
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property amountTo (base name: "amountTo")', function() {
      // uncomment below and update the code to test the property amountTo
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property assetName (base name: "assetName")', function() {
      // uncomment below and update the code to test the property assetName
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property filingDate (base name: "filingDate")', function() {
      // uncomment below and update the code to test the property filingDate
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property ownerType (base name: "ownerType")', function() {
      // uncomment below and update the code to test the property ownerType
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

    it('should have the property transactionType (base name: "transactionType")', function() {
      // uncomment below and update the code to test the property transactionType
      //var instance = new finnhub.CongressionalTransaction();
      //expect(instance).to.be();
    });

  });

}));
