/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.InstitutionalProfileInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstitutionalProfileInfo', function() {
    it('should create an instance of InstitutionalProfileInfo', function() {
      // uncomment below and update the code to test InstitutionalProfileInfo
      //var instane = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be.a(finnhub.InstitutionalProfileInfo);
    });

    it('should have the property cik (base name: "cik")', function() {
      // uncomment below and update the code to test the property cik
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

    it('should have the property firmType (base name: "firmType")', function() {
      // uncomment below and update the code to test the property firmType
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

    it('should have the property manager (base name: "manager")', function() {
      // uncomment below and update the code to test the property manager
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

    it('should have the property philosophy (base name: "philosophy")', function() {
      // uncomment below and update the code to test the property philosophy
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

    it('should have the property profile (base name: "profile")', function() {
      // uncomment below and update the code to test the property profile
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

    it('should have the property profileImg (base name: "profileImg")', function() {
      // uncomment below and update the code to test the property profileImg
      //var instance = new finnhub.InstitutionalProfileInfo();
      //expect(instance).to.be();
    });

  });

}));
