/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.LobbyingData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LobbyingData', function() {
    it('should create an instance of LobbyingData', function() {
      // uncomment below and update the code to test LobbyingData
      //var instane = new finnhub.LobbyingData();
      //expect(instance).to.be.a(finnhub.LobbyingData);
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property income (base name: "income")', function() {
      // uncomment below and update the code to test the property income
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property expenses (base name: "expenses")', function() {
      // uncomment below and update the code to test the property expenses
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property documentUrl (base name: "documentUrl")', function() {
      // uncomment below and update the code to test the property documentUrl
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property postedName (base name: "postedName")', function() {
      // uncomment below and update the code to test the property postedName
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "clientId")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property registrantId (base name: "registrantId")', function() {
      // uncomment below and update the code to test the property registrantId
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property senateId (base name: "senateId")', function() {
      // uncomment below and update the code to test the property senateId
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

    it('should have the property houseregistrantId (base name: "houseregistrantId")', function() {
      // uncomment below and update the code to test the property houseregistrantId
      //var instance = new finnhub.LobbyingData();
      //expect(instance).to.be();
    });

  });

}));
