/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.NewsSentiment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewsSentiment', function() {
    it('should create an instance of NewsSentiment', function() {
      // uncomment below and update the code to test NewsSentiment
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be.a(finnhub.NewsSentiment);
    });

    it('should have the property buzz (base name: "buzz")', function() {
      // uncomment below and update the code to test the property buzz
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

    it('should have the property companyNewsScore (base name: "companyNewsScore")', function() {
      // uncomment below and update the code to test the property companyNewsScore
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

    it('should have the property sectorAverageBullishPercent (base name: "sectorAverageBullishPercent")', function() {
      // uncomment below and update the code to test the property sectorAverageBullishPercent
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

    it('should have the property sectorAverageNewsScore (base name: "sectorAverageNewsScore")', function() {
      // uncomment below and update the code to test the property sectorAverageNewsScore
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

    it('should have the property sentiment (base name: "sentiment")', function() {
      // uncomment below and update the code to test the property sentiment
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instane = new finnhub.NewsSentiment();
      //expect(instance).to.be();
    });

  });

}));
