/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.StockSymbol();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StockSymbol', function() {
    it('should create an instance of StockSymbol', function() {
      // uncomment below and update the code to test StockSymbol
      //var instane = new finnhub.StockSymbol();
      //expect(instance).to.be.a(finnhub.StockSymbol);
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property displaySymbol (base name: "displaySymbol")', function() {
      // uncomment below and update the code to test the property displaySymbol
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property mic (base name: "mic")', function() {
      // uncomment below and update the code to test the property mic
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property figi (base name: "figi")', function() {
      // uncomment below and update the code to test the property figi
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new finnhub.StockSymbol();
      //expect(instance).to.be();
    });

  });

}));
