/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.UsaSpending();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsaSpending', function() {
    it('should create an instance of UsaSpending', function() {
      // uncomment below and update the code to test UsaSpending
      //var instane = new finnhub.UsaSpending();
      //expect(instance).to.be.a(finnhub.UsaSpending);
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property recipientName (base name: "recipientName")', function() {
      // uncomment below and update the code to test the property recipientName
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property recipientParentName (base name: "recipientParentName")', function() {
      // uncomment below and update the code to test the property recipientParentName
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property awardDescription (base name: "awardDescription")', function() {
      // uncomment below and update the code to test the property awardDescription
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property actionDate (base name: "actionDate")', function() {
      // uncomment below and update the code to test the property actionDate
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property totalValue (base name: "totalValue")', function() {
      // uncomment below and update the code to test the property totalValue
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceStartDate (base name: "performanceStartDate")', function() {
      // uncomment below and update the code to test the property performanceStartDate
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceEndDate (base name: "performanceEndDate")', function() {
      // uncomment below and update the code to test the property performanceEndDate
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property awardingAgencyName (base name: "awardingAgencyName")', function() {
      // uncomment below and update the code to test the property awardingAgencyName
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property awardingSubAgencyName (base name: "awardingSubAgencyName")', function() {
      // uncomment below and update the code to test the property awardingSubAgencyName
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property awardingOfficeName (base name: "awardingOfficeName")', function() {
      // uncomment below and update the code to test the property awardingOfficeName
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceCountry (base name: "performanceCountry")', function() {
      // uncomment below and update the code to test the property performanceCountry
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceCity (base name: "performanceCity")', function() {
      // uncomment below and update the code to test the property performanceCity
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceCounty (base name: "performanceCounty")', function() {
      // uncomment below and update the code to test the property performanceCounty
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceState (base name: "performanceState")', function() {
      // uncomment below and update the code to test the property performanceState
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceZipCode (base name: "performanceZipCode")', function() {
      // uncomment below and update the code to test the property performanceZipCode
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property performanceCongressionalDistrict (base name: "performanceCongressionalDistrict")', function() {
      // uncomment below and update the code to test the property performanceCongressionalDistrict
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property naicsCode (base name: "naicsCode")', function() {
      // uncomment below and update the code to test the property naicsCode
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

    it('should have the property permalink (base name: "permalink")', function() {
      // uncomment below and update the code to test the property permalink
      //var instance = new finnhub.UsaSpending();
      //expect(instance).to.be();
    });

  });

}));
