/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.finnhub);
  }
}(this, function(expect, finnhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new finnhub.VisaApplication();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VisaApplication', function() {
    it('should create an instance of VisaApplication', function() {
      // uncomment below and update the code to test VisaApplication
      //var instane = new finnhub.VisaApplication();
      //expect(instance).to.be.a(finnhub.VisaApplication);
    });

    it('should have the property year (base name: "year")', function() {
      // uncomment below and update the code to test the property year
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property quarter (base name: "quarter")', function() {
      // uncomment below and update the code to test the property quarter
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property symbol (base name: "symbol")', function() {
      // uncomment below and update the code to test the property symbol
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property caseNumber (base name: "caseNumber")', function() {
      // uncomment below and update the code to test the property caseNumber
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property caseStatus (base name: "caseStatus")', function() {
      // uncomment below and update the code to test the property caseStatus
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property receivedDate (base name: "receivedDate")', function() {
      // uncomment below and update the code to test the property receivedDate
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property visaClass (base name: "visaClass")', function() {
      // uncomment below and update the code to test the property visaClass
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property jobTitle (base name: "jobTitle")', function() {
      // uncomment below and update the code to test the property jobTitle
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property socCode (base name: "socCode")', function() {
      // uncomment below and update the code to test the property socCode
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property fullTimePosition (base name: "fullTimePosition")', function() {
      // uncomment below and update the code to test the property fullTimePosition
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property beginDate (base name: "beginDate")', function() {
      // uncomment below and update the code to test the property beginDate
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property employerName (base name: "employerName")', function() {
      // uncomment below and update the code to test the property employerName
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property worksiteAddress (base name: "worksiteAddress")', function() {
      // uncomment below and update the code to test the property worksiteAddress
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property worksiteCity (base name: "worksiteCity")', function() {
      // uncomment below and update the code to test the property worksiteCity
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property worksiteCounty (base name: "worksiteCounty")', function() {
      // uncomment below and update the code to test the property worksiteCounty
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property worksiteState (base name: "worksiteState")', function() {
      // uncomment below and update the code to test the property worksiteState
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property worksitePostalCode (base name: "worksitePostalCode")', function() {
      // uncomment below and update the code to test the property worksitePostalCode
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property wageRangeFrom (base name: "wageRangeFrom")', function() {
      // uncomment below and update the code to test the property wageRangeFrom
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property wageRangeTo (base name: "wageRangeTo")', function() {
      // uncomment below and update the code to test the property wageRangeTo
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property waveUnitOfPay (base name: "waveUnitOfPay")', function() {
      // uncomment below and update the code to test the property waveUnitOfPay
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property wageLevel (base name: "wageLevel")', function() {
      // uncomment below and update the code to test the property wageLevel
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

    it('should have the property h1bDependent (base name: "h1bDependent")', function() {
      // uncomment below and update the code to test the property h1bDependent
      //var instance = new finnhub.VisaApplication();
      //expect(instance).to.be();
    });

  });

}));
