/**
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AggregateIndicators from './model/AggregateIndicators';
import BasicFinancials from './model/BasicFinancials';
import BondCandles from './model/BondCandles';
import BondProfile from './model/BondProfile';
import BondTickData from './model/BondTickData';
import BreakdownItem from './model/BreakdownItem';
import Company from './model/Company';
import CompanyESG from './model/CompanyESG';
import CompanyEarningsQualityScore from './model/CompanyEarningsQualityScore';
import CompanyEarningsQualityScoreData from './model/CompanyEarningsQualityScoreData';
import CompanyExecutive from './model/CompanyExecutive';
import CompanyNews from './model/CompanyNews';
import CompanyNewsStatistics from './model/CompanyNewsStatistics';
import CompanyProfile from './model/CompanyProfile';
import CompanyProfile2 from './model/CompanyProfile2';
import CountryMetadata from './model/CountryMetadata';
import CovidInfo from './model/CovidInfo';
import CryptoCandles from './model/CryptoCandles';
import CryptoProfile from './model/CryptoProfile';
import CryptoSymbol from './model/CryptoSymbol';
import Development from './model/Development';
import Dividends from './model/Dividends';
import Dividends2 from './model/Dividends2';
import Dividends2Info from './model/Dividends2Info';
import ETFCountryExposureData from './model/ETFCountryExposureData';
import ETFHoldingsData from './model/ETFHoldingsData';
import ETFProfileData from './model/ETFProfileData';
import ETFSectorExposureData from './model/ETFSectorExposureData';
import ETFsCountryExposure from './model/ETFsCountryExposure';
import ETFsHoldings from './model/ETFsHoldings';
import ETFsProfile from './model/ETFsProfile';
import ETFsSectorExposure from './model/ETFsSectorExposure';
import EarningRelease from './model/EarningRelease';
import EarningResult from './model/EarningResult';
import EarningsCalendar from './model/EarningsCalendar';
import EarningsCallTranscripts from './model/EarningsCallTranscripts';
import EarningsCallTranscriptsList from './model/EarningsCallTranscriptsList';
import EarningsEstimates from './model/EarningsEstimates';
import EarningsEstimatesInfo from './model/EarningsEstimatesInfo';
import EbitEstimates from './model/EbitEstimates';
import EbitEstimatesInfo from './model/EbitEstimatesInfo';
import EbitdaEstimates from './model/EbitdaEstimates';
import EbitdaEstimatesInfo from './model/EbitdaEstimatesInfo';
import EconomicCalendar from './model/EconomicCalendar';
import EconomicCode from './model/EconomicCode';
import EconomicData from './model/EconomicData';
import EconomicDataInfo from './model/EconomicDataInfo';
import EconomicEvent from './model/EconomicEvent';
import FDAComitteeMeeting from './model/FDAComitteeMeeting';
import Filing from './model/Filing';
import FilingSentiment from './model/FilingSentiment';
import FinancialStatements from './model/FinancialStatements';
import FinancialsAsReported from './model/FinancialsAsReported';
import ForexCandles from './model/ForexCandles';
import ForexSymbol from './model/ForexSymbol';
import Forexrates from './model/Forexrates';
import FundOwnership from './model/FundOwnership';
import FundOwnershipInfo from './model/FundOwnershipInfo';
import HistoricalNBBO from './model/HistoricalNBBO';
import IPOCalendar from './model/IPOCalendar';
import IPOEvent from './model/IPOEvent';
import IndexHistoricalConstituent from './model/IndexHistoricalConstituent';
import Indicator from './model/Indicator';
import IndicesConstituents from './model/IndicesConstituents';
import IndicesHistoricalConstituents from './model/IndicesHistoricalConstituents';
import InsiderSentiments from './model/InsiderSentiments';
import InsiderSentimentsData from './model/InsiderSentimentsData';
import InsiderTransactions from './model/InsiderTransactions';
import InstitutionalOwnership from './model/InstitutionalOwnership';
import InstitutionalOwnershipGroup from './model/InstitutionalOwnershipGroup';
import InstitutionalOwnershipInfo from './model/InstitutionalOwnershipInfo';
import InstitutionalPortfolio from './model/InstitutionalPortfolio';
import InstitutionalPortfolioGroup from './model/InstitutionalPortfolioGroup';
import InstitutionalPortfolioInfo from './model/InstitutionalPortfolioInfo';
import InstitutionalProfile from './model/InstitutionalProfile';
import InstitutionalProfileInfo from './model/InstitutionalProfileInfo';
import InternationalFiling from './model/InternationalFiling';
import InvestmentThemePortfolio from './model/InvestmentThemePortfolio';
import InvestmentThemes from './model/InvestmentThemes';
import IsinChange from './model/IsinChange';
import IsinChangeInfo from './model/IsinChangeInfo';
import KeyCustomersSuppliers from './model/KeyCustomersSuppliers';
import LastBidAsk from './model/LastBidAsk';
import LobbyingData from './model/LobbyingData';
import LobbyingResult from './model/LobbyingResult';
import MarketNews from './model/MarketNews';
import MutualFundCountryExposure from './model/MutualFundCountryExposure';
import MutualFundCountryExposureData from './model/MutualFundCountryExposureData';
import MutualFundHoldings from './model/MutualFundHoldings';
import MutualFundHoldingsData from './model/MutualFundHoldingsData';
import MutualFundProfile from './model/MutualFundProfile';
import MutualFundProfileData from './model/MutualFundProfileData';
import MutualFundSectorExposure from './model/MutualFundSectorExposure';
import MutualFundSectorExposureData from './model/MutualFundSectorExposureData';
import NewsSentiment from './model/NewsSentiment';
import Ownership from './model/Ownership';
import OwnershipInfo from './model/OwnershipInfo';
import PatternRecognition from './model/PatternRecognition';
import PressRelease from './model/PressRelease';
import PriceMetrics from './model/PriceMetrics';
import PriceTarget from './model/PriceTarget';
import Quote from './model/Quote';
import RecommendationTrend from './model/RecommendationTrend';
import RedditSentimentContent from './model/RedditSentimentContent';
import Report from './model/Report';
import RevenueBreakdown from './model/RevenueBreakdown';
import RevenueEstimates from './model/RevenueEstimates';
import RevenueEstimatesInfo from './model/RevenueEstimatesInfo';
import SECSentimentAnalysis from './model/SECSentimentAnalysis';
import SectorMetric from './model/SectorMetric';
import SectorMetricData from './model/SectorMetricData';
import Sentiment from './model/Sentiment';
import SimilarityIndex from './model/SimilarityIndex';
import SimilarityIndexInfo from './model/SimilarityIndexInfo';
import SocialSentiment from './model/SocialSentiment';
import Split from './model/Split';
import StockCandles from './model/StockCandles';
import StockSymbol from './model/StockSymbol';
import StockTranscripts from './model/StockTranscripts';
import SupplyChainRelationships from './model/SupplyChainRelationships';
import SupportResistance from './model/SupportResistance';
import SymbolChange from './model/SymbolChange';
import SymbolChangeInfo from './model/SymbolChangeInfo';
import SymbolLookup from './model/SymbolLookup';
import SymbolLookupInfo from './model/SymbolLookupInfo';
import TechnicalAnalysis from './model/TechnicalAnalysis';
import TickData from './model/TickData';
import Transactions from './model/Transactions';
import TranscriptContent from './model/TranscriptContent';
import TranscriptParticipant from './model/TranscriptParticipant';
import Trend from './model/Trend';
import TwitterSentimentContent from './model/TwitterSentimentContent';
import UpgradeDowngrade from './model/UpgradeDowngrade';
import UsaSpending from './model/UsaSpending';
import UsaSpendingResult from './model/UsaSpendingResult';
import UsptoPatent from './model/UsptoPatent';
import UsptoPatentResult from './model/UsptoPatentResult';
import VisaApplication from './model/VisaApplication';
import VisaApplicationResult from './model/VisaApplicationResult';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var finnhub = require('index'); // See note below*.
* var xxxSvc = new finnhub.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new finnhub.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new finnhub.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new finnhub.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.2.16
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AggregateIndicators model constructor.
     * @property {module:model/AggregateIndicators}
     */
    AggregateIndicators,

    /**
     * The BasicFinancials model constructor.
     * @property {module:model/BasicFinancials}
     */
    BasicFinancials,

    /**
     * The BondCandles model constructor.
     * @property {module:model/BondCandles}
     */
    BondCandles,

    /**
     * The BondProfile model constructor.
     * @property {module:model/BondProfile}
     */
    BondProfile,

    /**
     * The BondTickData model constructor.
     * @property {module:model/BondTickData}
     */
    BondTickData,

    /**
     * The BreakdownItem model constructor.
     * @property {module:model/BreakdownItem}
     */
    BreakdownItem,

    /**
     * The Company model constructor.
     * @property {module:model/Company}
     */
    Company,

    /**
     * The CompanyESG model constructor.
     * @property {module:model/CompanyESG}
     */
    CompanyESG,

    /**
     * The CompanyEarningsQualityScore model constructor.
     * @property {module:model/CompanyEarningsQualityScore}
     */
    CompanyEarningsQualityScore,

    /**
     * The CompanyEarningsQualityScoreData model constructor.
     * @property {module:model/CompanyEarningsQualityScoreData}
     */
    CompanyEarningsQualityScoreData,

    /**
     * The CompanyExecutive model constructor.
     * @property {module:model/CompanyExecutive}
     */
    CompanyExecutive,

    /**
     * The CompanyNews model constructor.
     * @property {module:model/CompanyNews}
     */
    CompanyNews,

    /**
     * The CompanyNewsStatistics model constructor.
     * @property {module:model/CompanyNewsStatistics}
     */
    CompanyNewsStatistics,

    /**
     * The CompanyProfile model constructor.
     * @property {module:model/CompanyProfile}
     */
    CompanyProfile,

    /**
     * The CompanyProfile2 model constructor.
     * @property {module:model/CompanyProfile2}
     */
    CompanyProfile2,

    /**
     * The CountryMetadata model constructor.
     * @property {module:model/CountryMetadata}
     */
    CountryMetadata,

    /**
     * The CovidInfo model constructor.
     * @property {module:model/CovidInfo}
     */
    CovidInfo,

    /**
     * The CryptoCandles model constructor.
     * @property {module:model/CryptoCandles}
     */
    CryptoCandles,

    /**
     * The CryptoProfile model constructor.
     * @property {module:model/CryptoProfile}
     */
    CryptoProfile,

    /**
     * The CryptoSymbol model constructor.
     * @property {module:model/CryptoSymbol}
     */
    CryptoSymbol,

    /**
     * The Development model constructor.
     * @property {module:model/Development}
     */
    Development,

    /**
     * The Dividends model constructor.
     * @property {module:model/Dividends}
     */
    Dividends,

    /**
     * The Dividends2 model constructor.
     * @property {module:model/Dividends2}
     */
    Dividends2,

    /**
     * The Dividends2Info model constructor.
     * @property {module:model/Dividends2Info}
     */
    Dividends2Info,

    /**
     * The ETFCountryExposureData model constructor.
     * @property {module:model/ETFCountryExposureData}
     */
    ETFCountryExposureData,

    /**
     * The ETFHoldingsData model constructor.
     * @property {module:model/ETFHoldingsData}
     */
    ETFHoldingsData,

    /**
     * The ETFProfileData model constructor.
     * @property {module:model/ETFProfileData}
     */
    ETFProfileData,

    /**
     * The ETFSectorExposureData model constructor.
     * @property {module:model/ETFSectorExposureData}
     */
    ETFSectorExposureData,

    /**
     * The ETFsCountryExposure model constructor.
     * @property {module:model/ETFsCountryExposure}
     */
    ETFsCountryExposure,

    /**
     * The ETFsHoldings model constructor.
     * @property {module:model/ETFsHoldings}
     */
    ETFsHoldings,

    /**
     * The ETFsProfile model constructor.
     * @property {module:model/ETFsProfile}
     */
    ETFsProfile,

    /**
     * The ETFsSectorExposure model constructor.
     * @property {module:model/ETFsSectorExposure}
     */
    ETFsSectorExposure,

    /**
     * The EarningRelease model constructor.
     * @property {module:model/EarningRelease}
     */
    EarningRelease,

    /**
     * The EarningResult model constructor.
     * @property {module:model/EarningResult}
     */
    EarningResult,

    /**
     * The EarningsCalendar model constructor.
     * @property {module:model/EarningsCalendar}
     */
    EarningsCalendar,

    /**
     * The EarningsCallTranscripts model constructor.
     * @property {module:model/EarningsCallTranscripts}
     */
    EarningsCallTranscripts,

    /**
     * The EarningsCallTranscriptsList model constructor.
     * @property {module:model/EarningsCallTranscriptsList}
     */
    EarningsCallTranscriptsList,

    /**
     * The EarningsEstimates model constructor.
     * @property {module:model/EarningsEstimates}
     */
    EarningsEstimates,

    /**
     * The EarningsEstimatesInfo model constructor.
     * @property {module:model/EarningsEstimatesInfo}
     */
    EarningsEstimatesInfo,

    /**
     * The EbitEstimates model constructor.
     * @property {module:model/EbitEstimates}
     */
    EbitEstimates,

    /**
     * The EbitEstimatesInfo model constructor.
     * @property {module:model/EbitEstimatesInfo}
     */
    EbitEstimatesInfo,

    /**
     * The EbitdaEstimates model constructor.
     * @property {module:model/EbitdaEstimates}
     */
    EbitdaEstimates,

    /**
     * The EbitdaEstimatesInfo model constructor.
     * @property {module:model/EbitdaEstimatesInfo}
     */
    EbitdaEstimatesInfo,

    /**
     * The EconomicCalendar model constructor.
     * @property {module:model/EconomicCalendar}
     */
    EconomicCalendar,

    /**
     * The EconomicCode model constructor.
     * @property {module:model/EconomicCode}
     */
    EconomicCode,

    /**
     * The EconomicData model constructor.
     * @property {module:model/EconomicData}
     */
    EconomicData,

    /**
     * The EconomicDataInfo model constructor.
     * @property {module:model/EconomicDataInfo}
     */
    EconomicDataInfo,

    /**
     * The EconomicEvent model constructor.
     * @property {module:model/EconomicEvent}
     */
    EconomicEvent,

    /**
     * The FDAComitteeMeeting model constructor.
     * @property {module:model/FDAComitteeMeeting}
     */
    FDAComitteeMeeting,

    /**
     * The Filing model constructor.
     * @property {module:model/Filing}
     */
    Filing,

    /**
     * The FilingSentiment model constructor.
     * @property {module:model/FilingSentiment}
     */
    FilingSentiment,

    /**
     * The FinancialStatements model constructor.
     * @property {module:model/FinancialStatements}
     */
    FinancialStatements,

    /**
     * The FinancialsAsReported model constructor.
     * @property {module:model/FinancialsAsReported}
     */
    FinancialsAsReported,

    /**
     * The ForexCandles model constructor.
     * @property {module:model/ForexCandles}
     */
    ForexCandles,

    /**
     * The ForexSymbol model constructor.
     * @property {module:model/ForexSymbol}
     */
    ForexSymbol,

    /**
     * The Forexrates model constructor.
     * @property {module:model/Forexrates}
     */
    Forexrates,

    /**
     * The FundOwnership model constructor.
     * @property {module:model/FundOwnership}
     */
    FundOwnership,

    /**
     * The FundOwnershipInfo model constructor.
     * @property {module:model/FundOwnershipInfo}
     */
    FundOwnershipInfo,

    /**
     * The HistoricalNBBO model constructor.
     * @property {module:model/HistoricalNBBO}
     */
    HistoricalNBBO,

    /**
     * The IPOCalendar model constructor.
     * @property {module:model/IPOCalendar}
     */
    IPOCalendar,

    /**
     * The IPOEvent model constructor.
     * @property {module:model/IPOEvent}
     */
    IPOEvent,

    /**
     * The IndexHistoricalConstituent model constructor.
     * @property {module:model/IndexHistoricalConstituent}
     */
    IndexHistoricalConstituent,

    /**
     * The Indicator model constructor.
     * @property {module:model/Indicator}
     */
    Indicator,

    /**
     * The IndicesConstituents model constructor.
     * @property {module:model/IndicesConstituents}
     */
    IndicesConstituents,

    /**
     * The IndicesHistoricalConstituents model constructor.
     * @property {module:model/IndicesHistoricalConstituents}
     */
    IndicesHistoricalConstituents,

    /**
     * The InsiderSentiments model constructor.
     * @property {module:model/InsiderSentiments}
     */
    InsiderSentiments,

    /**
     * The InsiderSentimentsData model constructor.
     * @property {module:model/InsiderSentimentsData}
     */
    InsiderSentimentsData,

    /**
     * The InsiderTransactions model constructor.
     * @property {module:model/InsiderTransactions}
     */
    InsiderTransactions,

    /**
     * The InstitutionalOwnership model constructor.
     * @property {module:model/InstitutionalOwnership}
     */
    InstitutionalOwnership,

    /**
     * The InstitutionalOwnershipGroup model constructor.
     * @property {module:model/InstitutionalOwnershipGroup}
     */
    InstitutionalOwnershipGroup,

    /**
     * The InstitutionalOwnershipInfo model constructor.
     * @property {module:model/InstitutionalOwnershipInfo}
     */
    InstitutionalOwnershipInfo,

    /**
     * The InstitutionalPortfolio model constructor.
     * @property {module:model/InstitutionalPortfolio}
     */
    InstitutionalPortfolio,

    /**
     * The InstitutionalPortfolioGroup model constructor.
     * @property {module:model/InstitutionalPortfolioGroup}
     */
    InstitutionalPortfolioGroup,

    /**
     * The InstitutionalPortfolioInfo model constructor.
     * @property {module:model/InstitutionalPortfolioInfo}
     */
    InstitutionalPortfolioInfo,

    /**
     * The InstitutionalProfile model constructor.
     * @property {module:model/InstitutionalProfile}
     */
    InstitutionalProfile,

    /**
     * The InstitutionalProfileInfo model constructor.
     * @property {module:model/InstitutionalProfileInfo}
     */
    InstitutionalProfileInfo,

    /**
     * The InternationalFiling model constructor.
     * @property {module:model/InternationalFiling}
     */
    InternationalFiling,

    /**
     * The InvestmentThemePortfolio model constructor.
     * @property {module:model/InvestmentThemePortfolio}
     */
    InvestmentThemePortfolio,

    /**
     * The InvestmentThemes model constructor.
     * @property {module:model/InvestmentThemes}
     */
    InvestmentThemes,

    /**
     * The IsinChange model constructor.
     * @property {module:model/IsinChange}
     */
    IsinChange,

    /**
     * The IsinChangeInfo model constructor.
     * @property {module:model/IsinChangeInfo}
     */
    IsinChangeInfo,

    /**
     * The KeyCustomersSuppliers model constructor.
     * @property {module:model/KeyCustomersSuppliers}
     */
    KeyCustomersSuppliers,

    /**
     * The LastBidAsk model constructor.
     * @property {module:model/LastBidAsk}
     */
    LastBidAsk,

    /**
     * The LobbyingData model constructor.
     * @property {module:model/LobbyingData}
     */
    LobbyingData,

    /**
     * The LobbyingResult model constructor.
     * @property {module:model/LobbyingResult}
     */
    LobbyingResult,

    /**
     * The MarketNews model constructor.
     * @property {module:model/MarketNews}
     */
    MarketNews,

    /**
     * The MutualFundCountryExposure model constructor.
     * @property {module:model/MutualFundCountryExposure}
     */
    MutualFundCountryExposure,

    /**
     * The MutualFundCountryExposureData model constructor.
     * @property {module:model/MutualFundCountryExposureData}
     */
    MutualFundCountryExposureData,

    /**
     * The MutualFundHoldings model constructor.
     * @property {module:model/MutualFundHoldings}
     */
    MutualFundHoldings,

    /**
     * The MutualFundHoldingsData model constructor.
     * @property {module:model/MutualFundHoldingsData}
     */
    MutualFundHoldingsData,

    /**
     * The MutualFundProfile model constructor.
     * @property {module:model/MutualFundProfile}
     */
    MutualFundProfile,

    /**
     * The MutualFundProfileData model constructor.
     * @property {module:model/MutualFundProfileData}
     */
    MutualFundProfileData,

    /**
     * The MutualFundSectorExposure model constructor.
     * @property {module:model/MutualFundSectorExposure}
     */
    MutualFundSectorExposure,

    /**
     * The MutualFundSectorExposureData model constructor.
     * @property {module:model/MutualFundSectorExposureData}
     */
    MutualFundSectorExposureData,

    /**
     * The NewsSentiment model constructor.
     * @property {module:model/NewsSentiment}
     */
    NewsSentiment,

    /**
     * The Ownership model constructor.
     * @property {module:model/Ownership}
     */
    Ownership,

    /**
     * The OwnershipInfo model constructor.
     * @property {module:model/OwnershipInfo}
     */
    OwnershipInfo,

    /**
     * The PatternRecognition model constructor.
     * @property {module:model/PatternRecognition}
     */
    PatternRecognition,

    /**
     * The PressRelease model constructor.
     * @property {module:model/PressRelease}
     */
    PressRelease,

    /**
     * The PriceMetrics model constructor.
     * @property {module:model/PriceMetrics}
     */
    PriceMetrics,

    /**
     * The PriceTarget model constructor.
     * @property {module:model/PriceTarget}
     */
    PriceTarget,

    /**
     * The Quote model constructor.
     * @property {module:model/Quote}
     */
    Quote,

    /**
     * The RecommendationTrend model constructor.
     * @property {module:model/RecommendationTrend}
     */
    RecommendationTrend,

    /**
     * The RedditSentimentContent model constructor.
     * @property {module:model/RedditSentimentContent}
     */
    RedditSentimentContent,

    /**
     * The Report model constructor.
     * @property {module:model/Report}
     */
    Report,

    /**
     * The RevenueBreakdown model constructor.
     * @property {module:model/RevenueBreakdown}
     */
    RevenueBreakdown,

    /**
     * The RevenueEstimates model constructor.
     * @property {module:model/RevenueEstimates}
     */
    RevenueEstimates,

    /**
     * The RevenueEstimatesInfo model constructor.
     * @property {module:model/RevenueEstimatesInfo}
     */
    RevenueEstimatesInfo,

    /**
     * The SECSentimentAnalysis model constructor.
     * @property {module:model/SECSentimentAnalysis}
     */
    SECSentimentAnalysis,

    /**
     * The SectorMetric model constructor.
     * @property {module:model/SectorMetric}
     */
    SectorMetric,

    /**
     * The SectorMetricData model constructor.
     * @property {module:model/SectorMetricData}
     */
    SectorMetricData,

    /**
     * The Sentiment model constructor.
     * @property {module:model/Sentiment}
     */
    Sentiment,

    /**
     * The SimilarityIndex model constructor.
     * @property {module:model/SimilarityIndex}
     */
    SimilarityIndex,

    /**
     * The SimilarityIndexInfo model constructor.
     * @property {module:model/SimilarityIndexInfo}
     */
    SimilarityIndexInfo,

    /**
     * The SocialSentiment model constructor.
     * @property {module:model/SocialSentiment}
     */
    SocialSentiment,

    /**
     * The Split model constructor.
     * @property {module:model/Split}
     */
    Split,

    /**
     * The StockCandles model constructor.
     * @property {module:model/StockCandles}
     */
    StockCandles,

    /**
     * The StockSymbol model constructor.
     * @property {module:model/StockSymbol}
     */
    StockSymbol,

    /**
     * The StockTranscripts model constructor.
     * @property {module:model/StockTranscripts}
     */
    StockTranscripts,

    /**
     * The SupplyChainRelationships model constructor.
     * @property {module:model/SupplyChainRelationships}
     */
    SupplyChainRelationships,

    /**
     * The SupportResistance model constructor.
     * @property {module:model/SupportResistance}
     */
    SupportResistance,

    /**
     * The SymbolChange model constructor.
     * @property {module:model/SymbolChange}
     */
    SymbolChange,

    /**
     * The SymbolChangeInfo model constructor.
     * @property {module:model/SymbolChangeInfo}
     */
    SymbolChangeInfo,

    /**
     * The SymbolLookup model constructor.
     * @property {module:model/SymbolLookup}
     */
    SymbolLookup,

    /**
     * The SymbolLookupInfo model constructor.
     * @property {module:model/SymbolLookupInfo}
     */
    SymbolLookupInfo,

    /**
     * The TechnicalAnalysis model constructor.
     * @property {module:model/TechnicalAnalysis}
     */
    TechnicalAnalysis,

    /**
     * The TickData model constructor.
     * @property {module:model/TickData}
     */
    TickData,

    /**
     * The Transactions model constructor.
     * @property {module:model/Transactions}
     */
    Transactions,

    /**
     * The TranscriptContent model constructor.
     * @property {module:model/TranscriptContent}
     */
    TranscriptContent,

    /**
     * The TranscriptParticipant model constructor.
     * @property {module:model/TranscriptParticipant}
     */
    TranscriptParticipant,

    /**
     * The Trend model constructor.
     * @property {module:model/Trend}
     */
    Trend,

    /**
     * The TwitterSentimentContent model constructor.
     * @property {module:model/TwitterSentimentContent}
     */
    TwitterSentimentContent,

    /**
     * The UpgradeDowngrade model constructor.
     * @property {module:model/UpgradeDowngrade}
     */
    UpgradeDowngrade,

    /**
     * The UsaSpending model constructor.
     * @property {module:model/UsaSpending}
     */
    UsaSpending,

    /**
     * The UsaSpendingResult model constructor.
     * @property {module:model/UsaSpendingResult}
     */
    UsaSpendingResult,

    /**
     * The UsptoPatent model constructor.
     * @property {module:model/UsptoPatent}
     */
    UsptoPatent,

    /**
     * The UsptoPatentResult model constructor.
     * @property {module:model/UsptoPatentResult}
     */
    UsptoPatentResult,

    /**
     * The VisaApplication model constructor.
     * @property {module:model/VisaApplication}
     */
    VisaApplication,

    /**
     * The VisaApplicationResult model constructor.
     * @property {module:model/VisaApplicationResult}
     */
    VisaApplicationResult,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
